# R/compile.R ──────────────────────────────────────────────────────────────
# Public API: kst_compile() and kst_save().

#' Compile a JSON DSL table spec to a plain R script
#'
#' Reads a declarative JSON table specification, validates it (same checks as
#' \code{\link{kst_validate_spec}}), and generates a human-readable dplyr/tidyr
#' R script. The script expects a variable named \code{data} in its evaluation
#' environment. Calc and format functions referenced in the spec (e.g.
#' \code{"fun": "count"}) are emitted as bare calls and resolved from the same
#' environment at runtime — no lists to build, no registry to populate.
#'
#' Metadata (factor levels, ksformat labels) is \strong{not} applied during
#' compile. Use \code{\link{kst_extract_metadata}} and
#' \code{\link{kst_apply_metadata}} on \code{data} before evaluating the script
#' when \code{include_missing_levels} or group-header formatting is needed.
#' Optional \code{groups.format} entries in the JSON are documentation for that
#' pre-eval step (pass them as \code{format_map}); the compiler does not read them.
#'
#' @param json_spec  JSON string or path to a \code{.json} file.
#'
#' @return \code{character(1)} — a plain R script ready to be read, modified,
#'   saved, or executed with \code{eval(parse(text = code), envir = env)}.
#'
#' @seealso \code{\link{kst_save}}, \code{\link{kst_validate_spec}},
#'   \code{\link{kst_extract_metadata}}, \code{\link{kst_apply_metadata}}
#'
#' @examples
#' spec <- '{
#'   "schema_version": "1.0",
#'   "table_spec": {
#'     "parameter": { "age": { "variable": "AGE", "label": "Age (years)" } },
#'     "statistics": { "n": { "fun": "count" } },
#'     "groups": { "by": ["TRT"] },
#'     "layout": { "row_structure": "parameter_stat", "column_structure": "groups" }
#'   }
#' }'
#' cat(kst_compile(spec))
#'
#' @export
kst_compile <- function(json_spec) {
  json_spec <- read_json_spec(json_spec)
  assert_valid_spec(json_spec)
  spec <- jsonlite::fromJSON(json_spec, simplifyVector = FALSE)
  compile_ts(spec$table_spec)
}

# Accept a JSON string or a file path; always return a JSON string.
read_json_spec <- function(x) {
  stopifnot(is.character(x), length(x) == 1L)
  if (!startsWith(trimws(x), "{")) {
    if (!file.exists(x))
      stop("json_spec does not look like a JSON string and the path '",
           x, "' does not exist.", call. = FALSE)
    x <- paste(readLines(x, warn = FALSE), collapse = "\n")
  }
  x
}

# Fail fast with collected validation errors (shared by compile + save).
assert_valid_spec <- function(json_spec) {
  v <- kst_validate_spec(json_spec)
  if (!isTRUE(v$valid)) {
    stop("Invalid table specification:\n  ",
         paste(v$errors, collapse = "\n  "),
         call. = FALSE)
  }
  invisible(v)
}

#' Save a compiled table script to an R file
#'
#' Compiles the spec with \code{\link{kst_compile}} and writes the resulting
#' R script to a file with an informational header comment block.  The saved
#' file is a self-contained plain R script that can be read, reviewed, version-
#' controlled, or sourced directly.
#'
#' To execute the saved script:
#' \preformatted{
#' env      <- new.env(parent = environment())
#' env$data <- my_data
#' result   <- source("my_table.R", local = env)$value
#' }
#'
#' @param json_spec  JSON string or path to a \code{.json} file.
#' @param file       Output path (typically a \code{.R} file).
#' @param overwrite  Logical. If \code{FALSE} (default), stops when \code{file}
#'   already exists, protecting manually-edited scripts.
#'
#' @return The normalised absolute path to the written file, invisibly.
#'
#' @seealso \code{\link{kst_compile}}, \code{\link{kst_validate_spec}}
#'
#' @examples
#' spec <- '{
#'   "schema_version": "1.0",
#'   "table_spec": {
#'     "id": "demo",
#'     "parameter":  { "age": { "variable": "AGE" } },
#'     "statistics": { "n": { "fun": "length" } },
#'     "groups":     { "by": ["TRT"] },
#'     "layout":     { "row_structure": "parameter_stat" }
#'   }
#' }'
#' tmp <- tempfile(fileext = ".R")
#' kst_save(spec, tmp)
#' cat(readLines(tmp), sep = "\n")
#'
#' @export
kst_save <- function(json_spec, file, overwrite = FALSE) {
  if (!overwrite && file.exists(file))
    stop("'", file, "' already exists. Use overwrite = TRUE to replace it.",
         call. = FALSE)

  raw_json <- read_json_spec(json_spec)
  assert_valid_spec(raw_json)
  ts   <- jsonlite::fromJSON(raw_json, simplifyVector = FALSE)$table_spec
  code <- compile_ts(ts)

  ver   <- tryCatch(as.character(utils::packageVersion("ksTable")),
                    error = function(e) "?")
  fname <- basename(file)

  header <- c(
    paste0("# Generated by ksTable ", ver,
           "  (", format(Sys.time(), "%Y-%m-%d %H:%M"), ")"),
    paste0("# id:     ", ts$id    %||% "(none)"),
    paste0("# title:  ", ts$title %||% "(none)"),
    paste0("# layout: ", ts$layout$row_structure %||% "parameter_stat"),
    "#",
    "# Usage:",
    "#   env      <- new.env(parent = environment())",
    "#   env$data <- <your_data_frame>",
    paste0("#   result   <- source(\"", fname, "\", local = env)$value"),
    ""
  )

  writeLines(c(header, code), file)
  invisible(normalizePath(file))
}
